evaluate:
  type: "shell"
  timeout: 2500
  shell:
    entrypoint: "/bin/sh"
    logStderr: true
    command:
      - "-c"
      - "/cpa-rabbitmq-repair -mode=evaluate"

metric:
  type: "http"
  timeout: 2500
  http:
    method: "GET"
    url: "'http://prometheus-rabbitmq-exporter:9419/metric"
    successCodes:
      - 200
    parameterMode: query
minReplicas: 1
maxReplicas: 20
runMode: "per-resource"

# metric:
#   type: "shell"
#   timeout: 2500
#   shell:
#     entrypoint: "/bin/sh"
#     logStderr: true
#     command:
#       - "-c"
#       - "/cpa-rabbitmq-repair -mode=metric"
# runMode: "per-pod"

